EnvControlPanel/Controllers/RemoteCommandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using EnvControlPanel.Models;
using EnvControlPanel.Utils;

namespace EnvControlPanel.Controllers
{
    /// <summary>
    /// Controller for executing a command against a remote server.
    /// </summary>
    /// <remarks>Only the HTTP method POST is supported</remarks>
    public class RemoteCommandController : ApiController
    {
        /// <summary>
        /// HTTP Method POST
        /// </summary>
        /// <remarks>Creates a RemoteCommandRunner object and calls the executeCustomRemoteCommand() method.
        /// The request details are stored inside the rcr request object, and used internally when the executeCustomRemoteCommand()
        /// is invoked.</remarks>
        /// <returns>string</returns>
        public string Post(RemoteCommandRunner remoteCommandRequest)
        {
            
            return remoteCommandRequest.executeCustomRemoteCommand();
        }
    }
}

EnvControlPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar">
        <div class="container navbar navbar-inverse">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">BuilderTrend Environment Control Panel</a>
            </div>
            <div class="navbar-collapse collapse">
                <!--<ul class="nav nav-pills navbar-right">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Remote Command", "RemoteCommand", "Home")</li>
                    <li>@Html.ActionLink("Server Inventory", "Config", "Home")</li>
                </ul>-->      
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div class="container">
            <footer>
                <p>&copy; @DateTime.Now.Year - BuilderTrend</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>